# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 12.0.0.0b4.dev203\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-09-16 19:02+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova/filters.py:99
#, python-format
msgid "Filter %s returned 0 hosts"
msgstr ""

#: nova/filters.py:118
#, python-format
msgid ""
"Filtering removed all hosts for the request with reservation ID "
"'%(res_id)s' and instance ID '%(inst_uuid)s'. Filter results: "
"%(str_results)s"
msgstr ""

#: nova/service.py:161
#, python-format
msgid "Starting %(topic)s node (version %(version)s)"
msgstr ""

#: nova/utils.py:325
#, python-format
msgid "Executing RootwrapDaemonHelper.execute cmd=[%(cmd)r] kwargs=[%(kwargs)r]"
msgstr ""

#: nova/wsgi.py:154
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr ""

#: nova/wsgi.py:258
msgid "Stopping WSGI server."
msgstr ""

#: nova/wsgi.py:278
msgid "WSGI server has stopped."
msgstr ""

#: nova/api/ec2/__init__.py:466
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: nova/api/ec2/cloud.py:419
#, python-format
msgid "Create snapshot of volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:462
#, python-format
msgid "Create key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:474
#, python-format
msgid "Import key %s"
msgstr ""

#: nova/api/ec2/cloud.py:487
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:790
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: nova/api/ec2/cloud.py:863
#, python-format
msgid "Create volume from snapshot %s"
msgstr ""

#: nova/api/ec2/cloud.py:867
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:166
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: nova/api/ec2/cloud.py:907
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: nova/api/ec2/cloud.py:937
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:396
#, python-format
msgid "Detach volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:1304
msgid "Allocate address"
msgstr ""

#: nova/api/ec2/cloud.py:1309
#, python-format
msgid "Release address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1314
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1347
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1500
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: nova/api/ec2/cloud.py:1615
#, python-format
msgid "De-registering image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1651
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1720
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: nova/api/ec2/ec2utils.py:292
msgid "Timestamp is invalid."
msgstr ""

#: nova/api/openstack/__init__.py:111
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: nova/api/openstack/__init__.py:340
msgid "V2.1 API has been disabled by configuration"
msgstr ""

#: nova/api/openstack/__init__.py:393
#, python-format
msgid "Loaded extensions: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:531
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:534
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: nova/api/openstack/compute/assisted_volume_snapshots.py:56
#: nova/api/openstack/compute/legacy_v2/contrib/assisted_volume_snapshots.py:53
#, python-format
msgid "Create assisted snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/assisted_volume_snapshots.py:72
#: nova/api/openstack/compute/legacy_v2/contrib/assisted_volume_snapshots.py:64
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:505
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: nova/api/openstack/compute/hosts.py:139
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:160
#, python-format
msgid "Putting host %(host_name)s in maintenance mode %(mode)s."
msgstr ""

#: nova/api/openstack/compute/hosts.py:160
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:183
#, python-format
msgid "Enabling host %s."
msgstr ""

#: nova/api/openstack/compute/hosts.py:162
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:185
#, python-format
msgid "Disabling host %s."
msgstr ""

#: nova/api/openstack/compute/server_external_events.py:87
#: nova/api/openstack/compute/legacy_v2/contrib/server_external_events.py:103
#, python-format
msgid "Creating event %(name)s:%(tag)s for instance %(instance_uuid)s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:120
msgid "Attach interface"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:154
#, python-format
msgid "Detach interface %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:77
#, python-format
msgid "vol=%s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:111
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:299
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:543
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: nova/cells/messaging.py:1113
#, python-format
msgid ""
"Forcing a sync of instances, project_id=%(projid_str)s, "
"updated_since=%(since_str)s"
msgstr ""

#: nova/cells/scheduler.py:239
#, python-format
msgid ""
"No cells available when scheduling.  Will retry in %(sleep_time)s "
"second(s)"
msgstr ""

#: nova/cells/filters/target_cell.py:59
#, python-format
msgid ""
"Forcing direct route to %(cell_name)s because of 'target_cell' scheduler "
"hint"
msgstr ""

#: nova/compute/api.py:1584
msgid "instance termination disabled"
msgstr ""

#: nova/compute/api.py:1597
#, python-format
msgid "Working on deleting snapshot %s from shelved instance..."
msgstr ""

#: nova/compute/api.py:1667
msgid "Instance is already in deleting state, ignoring this request"
msgstr ""

#: nova/compute/api.py:1712
#, python-format
msgid ""
"Found an unconfirmed migration during delete, id: %(id)s, status: "
"%(status)s"
msgstr ""

#: nova/compute/api.py:1722
msgid "Instance may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1739
#, python-format
msgid "Migration %s may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1785
msgid ""
"instance is in SHELVED_OFFLOADED state, cleanup the instance's info from "
"database."
msgstr ""

#: nova/compute/api.py:2189
msgid "It's not supported to backup volume backed instance."
msgstr ""

#: nova/compute/api.py:2327
#, python-format
msgid "Skipping quiescing instance: %(reason)s."
msgstr ""

#: nova/compute/api.py:3899
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: nova/compute/api.py:4004
#, python-format
msgid "Delete security group %s"
msgstr ""

#: nova/compute/claims.py:148
msgid "Claim successful"
msgstr ""

#: nova/compute/claims.py:217
#, python-format
msgid "Total %(type)s: %(total)d %(unit)s, used: %(used).02f %(unit)s"
msgstr ""

#: nova/compute/claims.py:224
#, python-format
msgid "%(type)s limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/claims.py:231
#, python-format
msgid "%(type)s limit: %(limit).02f %(unit)s, free: %(free).02f %(unit)s"
msgstr ""

#: nova/compute/manager.py:327
#, python-format
msgid "Task possibly preempted: %s"
msgstr ""

#: nova/compute/manager.py:829
msgid "Deleting instance as it has been evacuated from this host"
msgstr ""

#: nova/compute/manager.py:841
msgid "Instance has been marked deleted already, removing it from the hypervisor."
msgstr ""

#: nova/compute/manager.py:1016
msgid ""
"Service started deleting the instance during the previous run, but did "
"not finish. Restarting the deletion now."
msgstr ""

#: nova/compute/manager.py:1149
msgid "Instance found in migrating state during startup. Resetting task_state"
msgstr ""

#: nova/compute/manager.py:1171
msgid "Rebooting instance after nova-compute restart."
msgstr ""

#: nova/compute/manager.py:1221
#, python-format
msgid "VM %(state)s (Lifecycle Event)"
msgstr ""

#: nova/compute/manager.py:1286
msgid ""
"Instance lifecycle events from the compute driver have been disabled. "
"Note that lifecycle changes to an instance outside of the compute service"
" will only be synchronized by the _sync_power_states periodic task."
msgstr ""

#: nova/compute/manager.py:1873
msgid "Starting instance..."
msgstr ""

#: nova/compute/manager.py:2243
#, python-format
msgid "%(action_str)s instance"
msgstr ""

#: nova/compute/manager.py:2409
msgid "Instance disappeared during terminate"
msgstr ""

#: nova/compute/manager.py:2453
msgid "Instance is already powered off in the hypervisor when stop is called."
msgstr ""

#: nova/compute/manager.py:2635
msgid "Rebuilding instance"
msgstr ""

#: nova/compute/manager.py:2672
msgid "disk on shared storage, recreating using existing disk"
msgstr ""

#: nova/compute/manager.py:2676
#, python-format
msgid "disk not on shared storage, rebuilding from: '%s'"
msgstr ""

#: nova/compute/manager.py:2770
#, python-format
msgid "bringing vm to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:2801
#, python-format
msgid "Detaching from volume api: %s"
msgstr ""

#: nova/compute/manager.py:2828
msgid "Rebooting instance"
msgstr ""

#: nova/compute/manager.py:2966
msgid "instance snapshotting"
msgstr ""

#: nova/compute/manager.py:3100
msgid "Root password set"
msgstr ""

#: nova/compute/manager.py:3148
#, python-format
msgid "injecting file to %s"
msgstr ""

#: nova/compute/manager.py:3183
msgid "Rescuing"
msgstr ""

#: nova/compute/manager.py:3231
msgid "Unrescuing"
msgstr ""

#: nova/compute/manager.py:3308
#, python-format
msgid "Migration %s is already confirmed"
msgstr ""

#: nova/compute/manager.py:3329
msgid "Instance is not found during confirmation"
msgstr ""

#: nova/compute/manager.py:3532
#, python-format
msgid "Updating instance to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:3582
msgid "Migrating"
msgstr ""

#: nova/compute/manager.py:3936
msgid "Pausing"
msgstr ""

#: nova/compute/manager.py:3952
msgid "Unpausing"
msgstr ""

#: nova/compute/manager.py:3989 nova/compute/manager.py:4006
msgid "Retrieving diagnostics"
msgstr ""

#: nova/compute/manager.py:4045
msgid "Resuming"
msgstr ""

#: nova/compute/manager.py:4284
msgid "Get console output"
msgstr ""

#: nova/compute/manager.py:4548
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:4573
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr ""

#: nova/compute/manager.py:4758
#, python-format
msgid "Swapping volume %(old_volume)s for %(new_volume)s"
msgstr ""

#: nova/compute/manager.py:5136
msgid "_post_live_migration() is started.."
msgstr ""

#: nova/compute/manager.py:5218
#, python-format
msgid "Migrating instance to %s finished successfully."
msgstr ""

#: nova/compute/manager.py:5220
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""

#: nova/compute/manager.py:5258
msgid "Post operation of migration started"
msgstr ""

#: nova/compute/manager.py:5540
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""

#: nova/compute/manager.py:5555
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""

#: nova/compute/manager.py:5609
#, python-format
msgid "Error auto-confirming resize: %s. Will retry later."
msgstr ""

#: nova/compute/manager.py:5659
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""

#: nova/compute/manager.py:5706
msgid "Updating bandwidth usage cache"
msgstr ""

#: nova/compute/manager.py:5894 nova/compute/manager.py:5951
#, python-format
msgid "During sync_power_state the instance has a pending task (%(task)s). Skip."
msgstr ""

#: nova/compute/manager.py:5938
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to"
" host %(dst)s"
msgstr ""

#: nova/compute/manager.py:5959
#, python-format
msgid ""
"During _sync_instance_power_state the DB power_state (%(db_power_state)s)"
" does not match the vm_power_state from the hypervisor "
"(%(vm_power_state)s). Updating power_state in the DB to match the "
"hypervisor."
msgstr ""

#: nova/compute/manager.py:6106
msgid "Reclaiming deleted instance"
msgstr ""

#: nova/compute/manager.py:6140
#, python-format
msgid "Compute node '%s' not found in update_available_resource."
msgstr ""

#: nova/compute/manager.py:6158
#, python-format
msgid "Deleting orphan compute node %s"
msgstr ""

#: nova/compute/manager.py:6208
#, python-format
msgid ""
"Powering off instance with name label '%s' which is marked as DELETED but"
" still present on host."
msgstr ""

#: nova/compute/manager.py:6226
#, python-format
msgid ""
"Destroying instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6274
#, python-format
msgid "Setting instance back to %(state)s after: %(error)s"
msgstr ""

#: nova/compute/manager.py:6284
#, python-format
msgid "Setting instance back to ACTIVE after: %s"
msgstr ""

#: nova/compute/manager.py:6347
#, python-format
msgid ""
"Neutron deleted interface %(intf)s; detaching it from the instance and "
"deleting it from the info cache"
msgstr ""

#: nova/compute/manager.py:6382
#, python-format
msgid "Failed to process external instance event %(event)s due to: %(error)s"
msgstr ""

#: nova/compute/resource_tracker.py:400
#, python-format
msgid "Compute_service record created for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:450
#, python-format
msgid "Auditing locally available compute resources for node %(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:457
msgid ""
"Virt driver does not support 'get_available_resource'. Compute tracking "
"is disabled."
msgstr ""

#: nova/compute/resource_tracker.py:537
#, python-format
msgid "Compute_service record updated for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:604
#, python-format
msgid "Total usable vcpus: %(tcpu)s, total allocated vcpus: %(ucpu)s"
msgstr ""

#: nova/compute/resource_tracker.py:612
#, python-format
msgid ""
"Final resource view: name=%(node)s phys_ram=%(phys_ram)sMB "
"used_ram=%(used_ram)sMB phys_disk=%(phys_disk)sGB "
"used_disk=%(used_disk)sGB total_vcpus=%(total_vcpus)s "
"used_vcpus=%(used_vcpus)s pci_stats=%(pci_stats)s"
msgstr ""

#: nova/compute/resource_tracker.py:696
#, python-format
msgid "Updating from migration %s"
msgstr ""

#: nova/conductor/api.py:177
msgid "nova-conductor connection established successfully"
msgstr ""

#: nova/consoleauth/manager.py:100
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s"
msgstr ""

#: nova/consoleauth/manager.py:125
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:3455
#, python-format
msgid ""
"quota_usages out of sync, updating. project_id: %(project_id)s, user_id: "
"%(user_id)s, resource: %(res)s, tracked usage: %(tracked_use)s, actual "
"usage: %(in_use)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:5270
#, python-format
msgid ""
"Volume(%s) has lower stats then what is in the database. Instance must "
"have been rebooted or crashed. Updating totals."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:36
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:36
msgid ""
"Skipped adding reservations_deleted_expire_idx because an equivalent "
"index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/274_update_instances_project_id_index.py:36
msgid ""
"Skipped adding instances_project_id_deleted_idx because an equivalent "
"index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/277_add_fixed_ip_updated_index.py:40
#: nova/db/sqlalchemy/migrate_repo/versions/295_add_virtual_interfaces_uuid_index.py:40
#, python-format
msgid "Skipped adding %s because an equivalent index already exists."
msgstr ""

#: nova/image/glance.py:352
#, python-format
msgid "Successfully transferred using %s"
msgstr ""

#: nova/image/s3.py:387
#, python-format
msgid "Image %s was deleted underneath us"
msgstr ""

#: nova/image/download/file.py:163
#, python-format
msgid "Copied %(source_file)s using %(module_str)s"
msgstr ""

#: nova/network/api.py:225 nova/network/neutronv2/api.py:1253
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr ""

#: nova/network/driver.py:42
#, python-format
msgid "Loading network driver '%s'"
msgstr ""

#: nova/network/floating_ips.py:176
#, python-format
msgid "Floating IP %s is not associated. Ignore."
msgstr ""

#: nova/network/floating_ips.py:549
#, python-format
msgid "Starting migration network for instance %s"
msgstr ""

#: nova/network/floating_ips.py:585
#, python-format
msgid "Finishing migration network for instance %s"
msgstr ""

#: nova/network/manager.py:337
#, python-format
msgid "Configured network %(network)s on host %(host)s"
msgstr ""

#: nova/network/manager.py:512
#, python-format
msgid "Allocated network: '%s' for instance"
msgstr ""

#: nova/network/manager.py:575
#, python-format
msgid "Network deallocated for instance (fixed ips: '%s')"
msgstr ""

#: nova/network/manager.py:1038
#, python-format
msgid "Unable to release %s because vif doesn't exist"
msgstr ""

#: nova/network/manager.py:1045
#, python-format
msgid "Unable to release %s because vif object doesn't exist"
msgstr ""

#: nova/network/manager.py:1139
#, python-format
msgid ""
"Ignoring request to release fixed IP %(address)s with MAC %(mac)s since "
"it is now associated with a new instance that is in the process of "
"allocating it's network."
msgstr ""

#: nova/network/minidns.py:201
#, python-format
msgid "deleted %s"
msgstr ""

#: nova/network/neutronv2/api.py:1732
#, python-format
msgid ""
"Port %s from network info_cache is no longer associated with instance in "
"Neutron. Removing from network info_cache."
msgstr ""

#: nova/network/security_group/neutron_driver.py:479
#: nova/network/security_group/neutron_driver.py:534
#, python-format
msgid "Adding security group %(security_group_id)s to port %(port_id)s"
msgstr ""

#: nova/scheduler/host_manager.py:460
#, python-format
msgid "Host filter ignoring hosts: %s"
msgstr ""

#: nova/scheduler/host_manager.py:471
#, python-format
msgid "Host filter forcing available hosts to %s"
msgstr ""

#: nova/scheduler/host_manager.py:474
#, python-format
msgid "No hosts matched due to not matching 'force_hosts' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:487
#, python-format
msgid "Host filter forcing available nodes to %s"
msgstr ""

#: nova/scheduler/host_manager.py:490
#, python-format
msgid "No nodes matched due to not matching 'force_nodes' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:572
#, python-format
msgid "Removing dead compute node %(host)s:%(node)s from scheduler"
msgstr ""

#: nova/scheduler/host_manager.py:634
#, python-format
msgid "Received an update from an unknown host '%s'. Re-created its InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:652
#, python-format
msgid ""
"Received a delete update from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:670
#, python-format
msgid ""
"The instance sync for host '%s' did not match. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:674
#, python-format
msgid "Successfully synced instances from host '%s'."
msgstr ""

#: nova/scheduler/host_manager.py:678
#, python-format
msgid ""
"Received a sync request from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/filters/utils.py:63
#, python-format
msgid "%(num_values)d values found, of which the minimum value will be used."
msgstr ""

#: nova/servicegroup/drivers/db.py:93
msgid "Recovered connection to nova-conductor for reporting service status."
msgstr ""

#: nova/servicegroup/drivers/mc.py:87
msgid "Recovered connection to memcache server for reporting service status."
msgstr ""

#: nova/virt/block_device.py:225
#, python-format
msgid "preserve multipath_id %s"
msgstr ""

#: nova/virt/block_device.py:447
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/driver.py:1450
#, python-format
msgid "Loading compute driver '%s'"
msgstr ""

#: nova/virt/firewall.py:173 nova/virt/libvirt/firewall.py:363
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""

#: nova/virt/firewall.py:443
#, python-format
msgid "instance chain %s disappeared during refresh, skipping"
msgstr ""

#: nova/virt/disk/mount/api.py:160
msgid "Device allocation failed. Will retry in 2 seconds."
msgstr ""

#: nova/virt/disk/mount/loop.py:35
#, python-format
msgid "Loop mount error: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:92 nova/virt/disk/mount/nbd.py:105
#, python-format
msgid "NBD mount error: %s"
msgstr ""

#: nova/virt/disk/vfs/api.py:72
msgid "Unable to import guestfs, falling back to VFSLocalFS"
msgstr ""

#: nova/virt/hyperv/basevolumeutils.py:75
msgid "The ISCSI initiator name can't be found. Choosing the default one"
msgstr ""

#: nova/virt/hyperv/vmops.py:260
msgid "Spawning new instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:379 nova/virt/vmwareapi/vmops.py:789
msgid "Using config drive for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:393 nova/virt/libvirt/driver.py:2944
#, python-format
msgid "Creating config drive at %(path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:443
msgid "Got request to destroy instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:496
msgid "Soft shutdown succeeded."
msgstr ""

#: nova/virt/ironic/driver.py:794
#, python-format
msgid "Config drive for instance %(instance)s on baremetal node %(node)s created."
msgstr ""

#: nova/virt/ironic/driver.py:818
#, python-format
msgid "Successfully provisioned Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:913
#, python-format
msgid "Successfully unprovisioned Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:945
#, python-format
msgid "Successfully rebooted Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:970
#, python-format
msgid "Successfully powered off Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:996
#, python-format
msgid "Successfully powered on Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:1202
msgid "Instance was successfully rebuilt"
msgstr ""

#: nova/virt/libvirt/driver.py:559
#, python-format
msgid "Connection event '%(enabled)d' reason '%(reason)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:785
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:790
msgid "Instance destroyed successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:800
msgid "Instance may be started again."
msgstr ""

#: nova/virt/libvirt/driver.py:810
msgid "Going to destroy instance again."
msgstr ""

#: nova/virt/libvirt/driver.py:1415
msgid "Beginning live snapshot process"
msgstr ""

#: nova/virt/libvirt/driver.py:1418
msgid "Beginning cold snapshot process"
msgstr ""

#: nova/virt/libvirt/driver.py:1449
msgid "Snapshot extracted, beginning image upload"
msgstr ""

#: nova/virt/libvirt/driver.py:1461
msgid "Snapshot image upload complete"
msgstr ""

#: nova/virt/libvirt/driver.py:2054
msgid "Instance soft rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2107
msgid "Instance shutdown successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2115
msgid "Instance may have been rebooted during soft reboot, so return now."
msgstr ""

#: nova/virt/libvirt/driver.py:2178
msgid "Instance rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2229
msgid "Instance already shutdown."
msgstr ""

#: nova/virt/libvirt/driver.py:2250
#, python-format
msgid "Instance shutdown successfully after %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2279
#, python-format
msgid "Instance failed to shutdown in %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2459
msgid "Instance spawned successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2475
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: nova/virt/libvirt/driver.py:2511
msgid ""
"Instance is configured with a file console, but the backing file is not "
"(yet?) present"
msgstr ""

#: nova/virt/libvirt/driver.py:2522 nova/virt/libvirt/driver.py:2549
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr ""

#: nova/virt/libvirt/driver.py:2808
msgid "Creating image"
msgstr ""

#: nova/virt/libvirt/driver.py:2935
msgid "Using config drive"
msgstr ""

#: nova/virt/libvirt/driver.py:3766
msgid "Configuring timezone for windows instance to localtime"
msgstr ""

#: nova/virt/libvirt/driver.py:4956
#, python-format
msgid ""
"Getting block stats failed, device might have been detached. "
"Instance=%(instance_name)s Disk=%(disk)s Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4963
#, python-format
msgid ""
"Could not find domain in libvirt for instance %s. Cannot get block stats "
"for device"
msgstr ""

#: nova/virt/libvirt/driver.py:5296
#, python-format
msgid "Instance launched has CPU info: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:5867
#, python-format
msgid "Error %(ex)s, migration failed"
msgstr ""

#: nova/virt/libvirt/driver.py:5920
#, python-format
msgid "Increasing downtime to %(downtime)dms after %(waittime)d sec elapsed time"
msgstr ""

#: nova/virt/libvirt/driver.py:5962
#, python-format
msgid ""
"Migration running for %(secs)d secs, memory %(remaining)d%% remaining; "
"(bytes processed=%(processed_memory)d, remaining=%(remaining_memory)d, "
"total=%(total_memory)d)"
msgstr ""

#: nova/virt/libvirt/driver.py:5972
#, python-format
msgid ""
"Data remaining %(remaining)d bytes, low watermark %(watermark)d bytes "
"%(last)d seconds ago"
msgstr ""

#: nova/virt/libvirt/driver.py:5982
msgid "Migration operation has completed"
msgstr ""

#: nova/virt/libvirt/driver.py:6750
msgid "Instance running successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:7133
#, python-format
msgid "Deleting instance files %s"
msgstr ""

#: nova/virt/libvirt/driver.py:7146
#, python-format
msgid "Deletion of %s failed"
msgstr ""

#: nova/virt/libvirt/driver.py:7150
#, python-format
msgid "Deletion of %s complete"
msgstr ""

#: nova/virt/libvirt/firewall.py:117
msgid "Called setup_basic_filtering in nwfilter"
msgstr ""

#: nova/virt/libvirt/firewall.py:125
msgid "Ensuring static filters"
msgstr ""

#: nova/virt/libvirt/firewall.py:289
#, python-format
msgid "Failed to undefine network filter %(name)s. Try %(cnt)d of %(max_retry)d."
msgstr ""

#: nova/virt/libvirt/host.py:716
#, python-format
msgid ""
"Unable to use bulk domain list APIs, falling back to slow code path: "
"%(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:766
#, python-format
msgid "Libvirt host capabilities %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:441
#, python-format
msgid "Failed to get image info from path %(path)s; error: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:193
#, python-format
msgid "Writing stored info to %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:416
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash "
"stored"
msgstr ""

#: nova/virt/libvirt/imagecache.py:425
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr ""

#: nova/virt/libvirt/imagecache.py:454
#, python-format
msgid "Base or swap file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:457
#, python-format
msgid "Removing base or swap file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:507
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr ""

#: nova/virt/libvirt/imagecache.py:530
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""

#: nova/virt/libvirt/imagecache.py:613
#, python-format
msgid "Active base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:616
#, python-format
msgid "Corrupt base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:620
#, python-format
msgid "Removable base files: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:149
#, python-format
msgid "tap-ctl check: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:477
msgid "findmnt tool is not installed"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:67
#, python-format
msgid "Mounted volume: %s"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:135
#, python-format
msgid "Fixing previous mount %s which was not unmounted correctly."
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:157
#, python-format
msgid "Trying to disconnected unmounted volume at %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:202
#, python-format
msgid "VMware vCenter version: %s"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:263
#, python-format
msgid "Moved virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:281
#, python-format
msgid "Copied virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:295
#, python-format
msgid "Deleted virtual disk %s."
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:162
#, python-format
msgid "Image %s is no longer used by this node. Pending deletion!"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:167
#, python-format
msgid "Image %s is no longer used. Deleting!"
msgstr ""

#: nova/virt/vmwareapi/images.py:380
#, python-format
msgid "Downloaded image file data %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/images.py:383 nova/virt/vmwareapi/images.py:449
msgid "The imported VM was unregistered"
msgstr ""

#: nova/virt/vmwareapi/images.py:444
#, python-format
msgid "Downloaded OVA image file %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1307
msgid "Destroyed the VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:896
msgid "Created linked-clone VM from snapshot"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1449 nova/virt/xenapi/vmops.py:1701
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1453 nova/virt/xenapi/vmops.py:1705
msgid "Automatically hard rebooting"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:464
#, python-format
msgid ""
"The volume's backing has been relocated to %s. Need to consolidate "
"backing disk file."
msgstr ""

#: nova/virt/xenapi/agent.py:396
msgid ""
"XenServer tools installed in this image are capable of network injection."
"  Networking files will not bemanipulated"
msgstr ""

#: nova/virt/xenapi/agent.py:404
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""

#: nova/virt/xenapi/agent.py:408
msgid "XenServer tools are not installed in this image"
msgstr ""

#: nova/virt/xenapi/host.py:76
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database:"
" assuming it is a worker VM and skip ping migration to a new host"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:397
#, python-format
msgid "VBD %s already detached"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:400
#, python-format
msgid ""
"VBD %(vbd_ref)s uplug failed with \"%(err)s\", attempt "
"%(num_attempt)d/%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:687
#, python-format
msgid "Deleted %s snapshots."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1330
#, python-format
msgid ""
"Image creation data, cacheable: %(cache)s, downloaded: %(downloaded)s "
"duration: %(duration).2f secs for image %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2173
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2469
msgid "Manipulating interface files directly"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2478
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1287
msgid "Starting halted instance found during reboot"
msgstr ""

#: nova/virt/xenapi/vmops.py:1491
msgid "Destroying VM"
msgstr ""

#: nova/virt/xenapi/volumeops.py:64
#, python-format
msgid "Connected volume (vdi_uuid): %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:127
#, python-format
msgid "Dev %(dev_number)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:149
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""

#: nova/vnc/xvp_proxy.py:96
#, python-format
msgid "Error in handshake format: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:102
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:117
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:137
#, python-format
msgid "Request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:140
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:150
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:157
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:177
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr ""

#: nova/volume/encryptors/luks.py:110
#, python-format
msgid "%s is not a valid LUKS device; formatting device for first use"
msgstr ""

