# Translations template for nova.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 13.0.0.0b4.dev129\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-03-10 06:20+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: nova/filters.py:99
#, python-format
msgid "Filter %s returned 0 hosts"
msgstr ""

#: nova/filters.py:125
#, python-format
msgid ""
"Filtering removed all hosts for the request with instance ID "
"'%(inst_uuid)s'. Filter results: %(str_results)s"
msgstr ""

#: nova/service.py:153
#, python-format
msgid ""
"Updating service version for %(binary)s on %(host)s from %(old)i to "
"%(new)i"
msgstr ""

#: nova/service.py:195
#, python-format
msgid "Starting %(topic)s node (version %(version)s)"
msgstr ""

#: nova/utils.py:324
#, python-format
msgid "Executing RootwrapDaemonHelper.execute cmd=[%(cmd)r] kwargs=[%(kwargs)r]"
msgstr ""

#: nova/wsgi.py:108
#, python-format
msgid "%(name)s listening on %(host)s:%(port)s"
msgstr ""

#: nova/wsgi.py:212
msgid "Stopping WSGI server."
msgstr ""

#: nova/wsgi.py:232
msgid "WSGI server has stopped."
msgstr ""

#: nova/api/ec2/ec2utils.py:292
msgid "Timestamp is invalid."
msgstr ""

#: nova/api/openstack/__init__.py:116
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: nova/api/openstack/__init__.py:371
msgid "V2.1 API has been disabled by configuration"
msgstr ""

#: nova/api/openstack/__init__.py:424
#, python-format
msgid "Loaded extensions: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:436
#, python-format
msgid "Fault thrown: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:439
#, python-format
msgid "HTTP exception thrown: %s"
msgstr ""

#: nova/api/openstack/compute/assisted_volume_snapshots.py:56
#: nova/api/openstack/compute/legacy_v2/contrib/assisted_volume_snapshots.py:53
#, python-format
msgid "Create assisted snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/assisted_volume_snapshots.py:72
#: nova/api/openstack/compute/legacy_v2/contrib/assisted_volume_snapshots.py:64
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:517
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: nova/api/openstack/compute/hosts.py:141
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:163
#, python-format
msgid "Putting host %(host_name)s in maintenance mode %(mode)s."
msgstr ""

#: nova/api/openstack/compute/hosts.py:162
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:186
#, python-format
msgid "Enabling host %s."
msgstr ""

#: nova/api/openstack/compute/hosts.py:164
#: nova/api/openstack/compute/legacy_v2/contrib/hosts.py:188
#, python-format
msgid "Disabling host %s."
msgstr ""

#: nova/api/openstack/compute/server_external_events.py:87
#: nova/api/openstack/compute/legacy_v2/contrib/server_external_events.py:103
#, python-format
msgid "Creating event %(name)s:%(tag)s for instance %(instance_uuid)s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:120
msgid "Attach interface"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:155
#, python-format
msgid "Detach interface %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:89
#, python-format
msgid "vol=%s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:123
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:178
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:311
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:408
#, python-format
msgid "Detach volume %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:555
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: nova/cells/messaging.py:1101
#, python-format
msgid ""
"Forcing a sync of instances, project_id=%(projid_str)s, "
"updated_since=%(since_str)s"
msgstr ""

#: nova/cells/scheduler.py:221
#, python-format
msgid ""
"No cells available when scheduling.  Will retry in %(sleep_time)s "
"second(s)"
msgstr ""

#: nova/cells/filters/target_cell.py:59
#, python-format
msgid ""
"Forcing direct route to %(cell_name)s because of 'target_cell' scheduler "
"hint"
msgstr ""

#: nova/compute/api.py:1147
#, python-format
msgid ""
"max count reduced from %(max_count)d to %(max_net_count)d due to network "
"port quota"
msgstr ""

#: nova/compute/api.py:1583
msgid "instance termination disabled"
msgstr ""

#: nova/compute/api.py:1596
#, python-format
msgid "Working on deleting snapshot %s from shelved instance..."
msgstr ""

#: nova/compute/api.py:1666
msgid "Instance is already in deleting state, ignoring this request"
msgstr ""

#: nova/compute/api.py:1711
#, python-format
msgid ""
"Found an unconfirmed migration during delete, id: %(id)s, status: "
"%(status)s"
msgstr ""

#: nova/compute/api.py:1721
msgid "Instance may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1738
#, python-format
msgid "Migration %s may have been confirmed during delete"
msgstr ""

#: nova/compute/api.py:1805
msgid ""
"instance is in SHELVED_OFFLOADED state, cleanup the instance's info from "
"database."
msgstr ""

#: nova/compute/api.py:2196
msgid "It's not supported to backup volume backed instance."
msgstr ""

#: nova/compute/api.py:2334 nova/virt/libvirt/driver.py:1866
#, python-format
msgid "Skipping quiescing instance: %(reason)s."
msgstr ""

#: nova/compute/api.py:4100
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: nova/compute/api.py:4205
#, python-format
msgid "Delete security group %s"
msgstr ""

#: nova/compute/claims.py:143
#, python-format
msgid ""
"Attempting claim: memory %(memory_mb)d MB, disk %(disk_gb)d GB, vcpus "
"%(vcpus)d CPU"
msgstr ""

#: nova/compute/claims.py:159
msgid "Claim successful"
msgstr ""

#: nova/compute/claims.py:237
#, python-format
msgid "Total %(type)s: %(total)d %(unit)s, used: %(used).02f %(unit)s"
msgstr ""

#: nova/compute/claims.py:244
#, python-format
msgid "%(type)s limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/claims.py:251
#, python-format
msgid "%(type)s limit: %(limit).02f %(unit)s, free: %(free).02f %(unit)s"
msgstr ""

#: nova/compute/manager.py:334
#, python-format
msgid "Task possibly preempted: %s"
msgstr ""

#: nova/compute/manager.py:348
#, python-format
msgid "Successfully reverted task state from %s on failure for instance."
msgstr ""

#: nova/compute/manager.py:732 nova/conductor/manager.py:159
#: nova/console/manager.py:68 nova/consoleauth/manager.py:73
msgid "Reloading compute RPC API"
msgstr ""

#: nova/compute/manager.py:845
msgid "Deleting instance as it has been evacuated from this host"
msgstr ""

#: nova/compute/manager.py:857
msgid "Instance has been marked deleted already, removing it from the hypervisor."
msgstr ""

#: nova/compute/manager.py:1033
msgid ""
"Service started deleting the instance during the previous run, but did "
"not finish. Restarting the deletion now."
msgstr ""

#: nova/compute/manager.py:1167
msgid "Instance found in migrating state during startup. Resetting task_state"
msgstr ""

#: nova/compute/manager.py:1189
msgid "Rebooting instance after nova-compute restart."
msgstr ""

#: nova/compute/manager.py:1239
#, python-format
msgid "VM %(state)s (Lifecycle Event)"
msgstr ""

#: nova/compute/manager.py:1304
msgid ""
"Instance lifecycle events from the compute driver have been disabled. "
"Note that lifecycle changes to an instance outside of the compute service"
" will only be synchronized by the _sync_power_states periodic task."
msgstr ""

#: nova/compute/manager.py:1828
#, python-format
msgid "Took %0.2f seconds to deallocate network for instance."
msgstr ""

#: nova/compute/manager.py:1926
#, python-format
msgid "Took %0.2f seconds to build instance."
msgstr ""

#: nova/compute/manager.py:2040
#, python-format
msgid "Took %0.2f seconds to spawn the instance on the hypervisor."
msgstr ""

#: nova/compute/manager.py:2286
msgid "Terminating instance"
msgstr ""

#: nova/compute/manager.py:2309
#, python-format
msgid "Took %0.2f seconds to destroy the instance on the hypervisor."
msgstr ""

#: nova/compute/manager.py:2351
#, python-format
msgid "Took %(time).2f seconds to detach %(num)s volumes for instance."
msgstr ""

#: nova/compute/manager.py:2480
msgid "Instance disappeared during terminate"
msgstr ""

#: nova/compute/manager.py:2524
msgid "Instance is already powered off in the hypervisor when stop is called."
msgstr ""

#: nova/compute/manager.py:2746
msgid "Rebuilding instance"
msgstr ""

#: nova/compute/manager.py:2857
msgid "disk on shared storage, recreating using existing disk"
msgstr ""

#: nova/compute/manager.py:2861
#, python-format
msgid "disk not on shared storage, rebuilding from: '%s'"
msgstr ""

#: nova/compute/manager.py:2942
#, python-format
msgid "bringing vm to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:2973
#, python-format
msgid "Detaching from volume api: %s"
msgstr ""

#: nova/compute/manager.py:3000
msgid "Rebooting instance"
msgstr ""

#: nova/compute/manager.py:3136
msgid "instance snapshotting"
msgstr ""

#: nova/compute/manager.py:3270
msgid "Root password set"
msgstr ""

#: nova/compute/manager.py:3318
#, python-format
msgid "injecting file to %s"
msgstr ""

#: nova/compute/manager.py:3351
msgid "Rescuing"
msgstr ""

#: nova/compute/manager.py:3400
msgid "Unrescuing"
msgstr ""

#: nova/compute/manager.py:3454
#, python-format
msgid "Migration %s is already confirmed"
msgstr ""

#: nova/compute/manager.py:3475
msgid "Instance is not found during confirmation"
msgstr ""

#: nova/compute/manager.py:3672
#, python-format
msgid "Updating instance to original state: '%s'"
msgstr ""

#: nova/compute/manager.py:3722
msgid "Migrating"
msgstr ""

#: nova/compute/manager.py:4077
msgid "Pausing"
msgstr ""

#: nova/compute/manager.py:4093
msgid "Unpausing"
msgstr ""

#: nova/compute/manager.py:4130 nova/compute/manager.py:4147
msgid "Retrieving diagnostics"
msgstr ""

#: nova/compute/manager.py:4186
msgid "Resuming"
msgstr ""

#: nova/compute/manager.py:4429
msgid "Get console output"
msgstr ""

#: nova/compute/manager.py:4697
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:4722
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr ""

#: nova/compute/manager.py:4950
#, python-format
msgid "Swapping volume %(old_volume)s for %(new_volume)s"
msgstr ""

#: nova/compute/manager.py:5397
msgid "_post_live_migration() is started.."
msgstr ""

#: nova/compute/manager.py:5479
#, python-format
msgid "Migrating instance to %s finished successfully."
msgstr ""

#: nova/compute/manager.py:5481
msgid ""
"You may see the error \"libvirt: QEMU error: Domain not found: no domain "
"with matching name.\" This error can be safely ignored."
msgstr ""

#: nova/compute/manager.py:5519
msgid "Post operation of migration started"
msgstr ""

#: nova/compute/manager.py:5831
#, python-format
msgid ""
"Found %(migration_count)d unconfirmed migrations older than "
"%(confirm_window)d seconds"
msgstr ""

#: nova/compute/manager.py:5846
#, python-format
msgid ""
"Automatically confirming migration %(migration_id)s for instance "
"%(instance_uuid)s"
msgstr ""

#: nova/compute/manager.py:5900
#, python-format
msgid "Error auto-confirming resize: %s. Will retry later."
msgstr ""

#: nova/compute/manager.py:5952
#, python-format
msgid ""
"Running instance usage audit for host %(host)s from %(begin_time)s to "
"%(end_time)s. %(number_instances)s instances."
msgstr ""

#: nova/compute/manager.py:5999
msgid "Updating bandwidth usage cache"
msgstr ""

#: nova/compute/manager.py:6021
msgid "Bandwidth usage not supported by hypervisor."
msgstr ""

#: nova/compute/manager.py:6184 nova/compute/manager.py:6241
#, python-format
msgid "During sync_power_state the instance has a pending task (%(task)s). Skip."
msgstr ""

#: nova/compute/manager.py:6228
#, python-format
msgid ""
"During the sync_power process the instance has moved from host %(src)s to"
" host %(dst)s"
msgstr ""

#: nova/compute/manager.py:6249
#, python-format
msgid ""
"During _sync_instance_power_state the DB power_state (%(db_power_state)s)"
" does not match the vm_power_state from the hypervisor "
"(%(vm_power_state)s). Updating power_state in the DB to match the "
"hypervisor."
msgstr ""

#: nova/compute/manager.py:6396
msgid "Reclaiming deleted instance"
msgstr ""

#: nova/compute/manager.py:6429
#, python-format
msgid "Compute node '%s' not found in update_available_resource."
msgstr ""

#: nova/compute/manager.py:6446
#, python-format
msgid "Deleting orphan compute node %s"
msgstr ""

#: nova/compute/manager.py:6496
#, python-format
msgid ""
"Powering off instance with name label '%s' which is marked as DELETED but"
" still present on host."
msgstr ""

#: nova/compute/manager.py:6514
#, python-format
msgid ""
"Destroying instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6562
#, python-format
msgid "Setting instance back to %(state)s after: %(error)s"
msgstr ""

#: nova/compute/manager.py:6572
#, python-format
msgid "Setting instance back to ACTIVE after: %s"
msgstr ""

#: nova/compute/manager.py:6635
#, python-format
msgid ""
"Neutron deleted interface %(intf)s; detaching it from the instance and "
"deleting it from the info cache"
msgstr ""

#: nova/compute/manager.py:6670
#, python-format
msgid "Failed to process external instance event %(event)s due to: %(error)s"
msgstr ""

#: nova/compute/resource_tracker.py:447
#, python-format
msgid "Compute_service record created for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:500
#, python-format
msgid "Auditing locally available compute resources for node %(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:507
msgid ""
"Virt driver does not support 'get_available_resource'. Compute tracking "
"is disabled."
msgstr ""

#: nova/compute/resource_tracker.py:603
#, python-format
msgid "Compute_service record updated for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:670
#, python-format
msgid "Total usable vcpus: %(tcpu)s, total allocated vcpus: %(ucpu)s"
msgstr ""

#: nova/compute/resource_tracker.py:679
#, python-format
msgid ""
"Final resource view: name=%(node)s phys_ram=%(phys_ram)sMB "
"used_ram=%(used_ram)sMB phys_disk=%(phys_disk)sGB "
"used_disk=%(used_disk)sGB total_vcpus=%(total_vcpus)s "
"used_vcpus=%(used_vcpus)s pci_stats=%(pci_stats)s"
msgstr ""

#: nova/compute/resource_tracker.py:765
#, python-format
msgid "Updating from migration %s"
msgstr ""

#: nova/compute/rpcapi.py:374
#, python-format
msgid ""
"Automatically selected compute RPC version %(rpc)s from minimum service "
"version %(service)i"
msgstr ""

#: nova/conductor/api.py:159
msgid "nova-conductor connection established successfully"
msgstr ""

#: nova/consoleauth/manager.py:120
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s"
msgstr ""

#: nova/consoleauth/manager.py:145
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:3717
#, python-format
msgid ""
"quota_usages out of sync, updating. project_id: %(project_id)s, user_id: "
"%(user_id)s, resource: %(res)s, tracked usage: %(tracked_use)s, actual "
"usage: %(in_use)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:5587
#, python-format
msgid ""
"Volume(%s) has lower stats then what is in the database. Instance must "
"have been rebooted or crashed. Updating totals."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:36
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:36
msgid ""
"Skipped adding reservations_deleted_expire_idx because an equivalent "
"index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/274_update_instances_project_id_index.py:36
msgid ""
"Skipped adding instances_project_id_deleted_idx because an equivalent "
"index already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/277_add_fixed_ip_updated_index.py:40
#: nova/db/sqlalchemy/migrate_repo/versions/295_add_virtual_interfaces_uuid_index.py:40
#: nova/db/sqlalchemy/migrate_repo/versions/319_add_instances_deleted_created_at_index.py:42
#, python-format
msgid "Skipped adding %s because an equivalent index already exists."
msgstr ""

#: nova/image/glance.py:368
#, python-format
msgid "Successfully transferred using %s"
msgstr ""

#: nova/image/glance.py:420
#, python-format
msgid "Image signature verification succeeded for image: %s"
msgstr ""

#: nova/image/glance.py:436
#, python-format
msgid "Image signature verification succeeded for image %s"
msgstr ""

#: nova/image/s3.py:386
#, python-format
msgid "Image %s was deleted underneath us"
msgstr ""

#: nova/image/download/file.py:163
#, python-format
msgid "Copied %(source_file)s using %(module_str)s"
msgstr ""

#: nova/network/api.py:225 nova/network/neutronv2/api.py:1258
#, python-format
msgid "re-assign floating IP %(address)s from instance %(instance_id)s"
msgstr ""

#: nova/network/driver.py:42
#, python-format
msgid "Loading network driver '%s'"
msgstr ""

#: nova/network/floating_ips.py:176
#, python-format
msgid "Floating IP %s is not associated. Ignore."
msgstr ""

#: nova/network/floating_ips.py:549
#, python-format
msgid "Starting migration network for instance %s"
msgstr ""

#: nova/network/floating_ips.py:585
#, python-format
msgid "Finishing migration network for instance %s"
msgstr ""

#: nova/network/manager.py:336
#, python-format
msgid "Configured network %(network)s on host %(host)s"
msgstr ""

#: nova/network/manager.py:511
#, python-format
msgid "Allocated network: '%s' for instance"
msgstr ""

#: nova/network/manager.py:574
#, python-format
msgid "Network deallocated for instance (fixed IPs: '%s')"
msgstr ""

#: nova/network/manager.py:1037
#, python-format
msgid "Unable to release %s because vif doesn't exist"
msgstr ""

#: nova/network/manager.py:1044
#, python-format
msgid "Unable to release %s because vif object doesn't exist"
msgstr ""

#: nova/network/manager.py:1138
#, python-format
msgid ""
"Ignoring request to release fixed IP %(address)s with MAC %(mac)s since "
"it is now associated with a new instance that is in the process of "
"allocating it's network."
msgstr ""

#: nova/network/minidns.py:193
#, python-format
msgid "deleted %s"
msgstr ""

#: nova/network/neutronv2/api.py:1746
#, python-format
msgid ""
"Port %s from network info_cache is no longer associated with instance in "
"Neutron. Removing from network info_cache."
msgstr ""

#: nova/network/security_group/neutron_driver.py:477
#: nova/network/security_group/neutron_driver.py:532
#, python-format
msgid "Adding security group %(security_group_id)s to port %(port_id)s"
msgstr ""

#: nova/scheduler/host_manager.py:474
#, python-format
msgid "Host filter ignoring hosts: %s"
msgstr ""

#: nova/scheduler/host_manager.py:485
#, python-format
msgid "Host filter forcing available hosts to %s"
msgstr ""

#: nova/scheduler/host_manager.py:488
#, python-format
msgid "No hosts matched due to not matching 'force_hosts' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:501
#, python-format
msgid "Host filter forcing available nodes to %s"
msgstr ""

#: nova/scheduler/host_manager.py:504
#, python-format
msgid "No nodes matched due to not matching 'force_nodes' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:586
#, python-format
msgid "Removing dead compute node %(host)s:%(node)s from scheduler"
msgstr ""

#: nova/scheduler/host_manager.py:652
#, python-format
msgid "Received an update from an unknown host '%s'. Re-created its InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:670
#, python-format
msgid ""
"Received a delete update from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:688
#, python-format
msgid ""
"The instance sync for host '%s' did not match. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/host_manager.py:692
#, python-format
msgid "Successfully synced instances from host '%s'."
msgstr ""

#: nova/scheduler/host_manager.py:696
#, python-format
msgid ""
"Received a sync request from an unknown host '%s'. Re-created its "
"InstanceList."
msgstr ""

#: nova/scheduler/filters/retry_filter.py:47
#, python-format
msgid "Host %(host)s fails.  Previously tried hosts: %(hosts)s"
msgstr ""

#: nova/scheduler/filters/utils.py:64
#, python-format
msgid "%(num_values)d values found, of which the minimum value will be used."
msgstr ""

#: nova/scheduler/filters/utils.py:68
#, python-format
msgid "%(num_values)d values found, of which the maximum value will be used."
msgstr ""

#: nova/servicegroup/drivers/db.py:96
msgid "Recovered from being unable to report status."
msgstr ""

#: nova/servicegroup/drivers/mc.py:85
msgid "Recovered connection to memcache server for reporting service status."
msgstr ""

#: nova/virt/block_device.py:248
#, python-format
msgid "preserve multipath_id %s"
msgstr ""

#: nova/virt/block_device.py:494
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/block_device.py:500
#, python-format
msgid "Booting with volume snapshot %(snapshot_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/block_device.py:506
#, python-format
msgid "Booting with volume-backed-image %(image_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/block_device.py:512
#, python-format
msgid "Booting with blank volume at %(mountpoint)s"
msgstr ""

#: nova/virt/driver.py:1618
#, python-format
msgid "Loading compute driver '%s'"
msgstr ""

#: nova/virt/firewall.py:141 nova/virt/libvirt/firewall.py:355
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""

#: nova/virt/firewall.py:394
#, python-format
msgid "instance chain %s disappeared during refresh, skipping"
msgstr ""

#: nova/virt/osinfo.py:43
#, python-format
msgid "Cannot load Libosinfo: (%s)"
msgstr ""

#: nova/virt/disk/mount/api.py:167
msgid "Device allocation failed. Will retry in 2 seconds."
msgstr ""

#: nova/virt/disk/mount/loop.py:35
#, python-format
msgid "Loop mount error: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:84 nova/virt/disk/mount/nbd.py:97
#, python-format
msgid "NBD mount error: %s"
msgstr ""

#: nova/virt/disk/vfs/api.py:72
msgid "Unable to import guestfs, falling back to VFSLocalFS"
msgstr ""

#: nova/virt/hyperv/vmops.py:265
msgid "Spawning new instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:382 nova/virt/vmwareapi/vmops.py:825
msgid "Using config drive for instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:396 nova/virt/libvirt/driver.py:3255
#, python-format
msgid "Creating config drive at %(path)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:446
msgid "Got request to destroy instance"
msgstr ""

#: nova/virt/hyperv/vmops.py:503
msgid "Soft shutdown succeeded."
msgstr ""

#: nova/virt/ironic/driver.py:750
#, python-format
msgid "Config drive for instance %(instance)s on baremetal node %(node)s created."
msgstr ""

#: nova/virt/ironic/driver.py:772
#, python-format
msgid "Successfully provisioned Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:867
#, python-format
msgid "Successfully unprovisioned Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:898
#, python-format
msgid "Successfully rebooted Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:922
#, python-format
msgid "Successfully powered off Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:947
#, python-format
msgid "Successfully powered on Ironic node %s"
msgstr ""

#: nova/virt/ironic/driver.py:1139
msgid "Instance was successfully rebuilt"
msgstr ""

#: nova/virt/libvirt/driver.py:634
#, python-format
msgid "Connection event '%(enabled)d' reason '%(reason)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:994
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:999
msgid "Instance destroyed successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:1009
msgid "Instance may be started again."
msgstr ""

#: nova/virt/libvirt/driver.py:1019
msgid "Going to destroy instance again."
msgstr ""

#: nova/virt/libvirt/driver.py:1679
msgid "Beginning live snapshot process"
msgstr ""

#: nova/virt/libvirt/driver.py:1682
msgid "Beginning cold snapshot process"
msgstr ""

#: nova/virt/libvirt/driver.py:1728
msgid "Snapshot extracted, beginning image upload"
msgstr ""

#: nova/virt/libvirt/driver.py:1749
msgid "Snapshot image upload complete"
msgstr ""

#: nova/virt/libvirt/driver.py:2395
msgid "Instance soft rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2440
msgid "Instance shutdown successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2448
msgid "Instance may have been rebooted during soft reboot, so return now."
msgstr ""

#: nova/virt/libvirt/driver.py:2509
msgid "Instance rebooted successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2549
msgid "Instance already shutdown."
msgstr ""

#: nova/virt/libvirt/driver.py:2564
#, python-format
msgid "Instance shutdown successfully after %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2593
#, python-format
msgid "Instance failed to shutdown in %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2774
msgid "Instance spawned successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:2790
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr ""

#: nova/virt/libvirt/driver.py:2826
msgid ""
"Instance is configured with a file console, but the backing file is not "
"(yet?) present"
msgstr ""

#: nova/virt/libvirt/driver.py:2837 nova/virt/libvirt/driver.py:2864
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr ""

#: nova/virt/libvirt/driver.py:3117
msgid "Creating image"
msgstr ""

#: nova/virt/libvirt/driver.py:3246
msgid "Using config drive"
msgstr ""

#: nova/virt/libvirt/driver.py:4112
msgid "Configuring timezone for windows instance to localtime"
msgstr ""

#: nova/virt/libvirt/driver.py:5310
#, python-format
msgid ""
"Getting block stats failed, device might have been detached. "
"Instance=%(instance_name)s Disk=%(disk)s Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5317
#, python-format
msgid ""
"Could not find domain in libvirt for instance %s. Cannot get block stats "
"for device"
msgstr ""

#: nova/virt/libvirt/driver.py:5668
#, python-format
msgid "Instance launched has CPU info: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:6282
#, python-format
msgid "Error %(ex)s, migration failed"
msgstr ""

#: nova/virt/libvirt/driver.py:6335
#, python-format
msgid "Increasing downtime to %(downtime)d ms after %(waittime)d sec elapsed time"
msgstr ""

#: nova/virt/libvirt/driver.py:6387
#, python-format
msgid ""
"Migration running for %(secs)d secs, memory %(remaining)d%% remaining; "
"(bytes processed=%(processed_memory)d, remaining=%(remaining_memory)d, "
"total=%(total_memory)d)"
msgstr ""

#: nova/virt/libvirt/driver.py:6397
#, python-format
msgid ""
"Data remaining %(remaining)d bytes, low watermark %(watermark)d bytes "
"%(last)d seconds ago"
msgstr ""

#: nova/virt/libvirt/driver.py:6407
msgid "Migration operation has completed"
msgstr ""

#: nova/virt/libvirt/driver.py:7247
msgid "Instance running successfully."
msgstr ""

#: nova/virt/libvirt/driver.py:7648
#, python-format
msgid "Deleting instance files %s"
msgstr ""

#: nova/virt/libvirt/driver.py:7661
#, python-format
msgid "Deletion of %s failed"
msgstr ""

#: nova/virt/libvirt/driver.py:7665
#, python-format
msgid "Deletion of %s complete"
msgstr ""

#: nova/virt/libvirt/firewall.py:115
msgid "Called setup_basic_filtering in nwfilter"
msgstr ""

#: nova/virt/libvirt/firewall.py:123
msgid "Ensuring static filters"
msgstr ""

#: nova/virt/libvirt/firewall.py:287
#, python-format
msgid "Failed to undefine network filter %(name)s. Try %(cnt)d of %(max_retry)d."
msgstr ""

#: nova/virt/libvirt/host.py:730
#, python-format
msgid ""
"Unable to use bulk domain list APIs, falling back to slow code path: "
"%(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:780
#, python-format
msgid "Libvirt host capabilities %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:492
#, python-format
msgid "Failed to get image info from path %(path)s; error: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:192
#, python-format
msgid "Writing stored info to %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:415
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash "
"stored"
msgstr ""

#: nova/virt/libvirt/imagecache.py:424
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr ""

#: nova/virt/libvirt/imagecache.py:464
#, python-format
msgid "Removing base or swap file: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:478
#, python-format
msgid "Base or swap file too young to remove: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:518
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr ""

#: nova/virt/libvirt/imagecache.py:541
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""

#: nova/virt/libvirt/imagecache.py:622
#, python-format
msgid "Active base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:625
#, python-format
msgid "Corrupt base files: %s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:629
#, python-format
msgid "Removable base files: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:152
#, python-format
msgid "tap-ctl check: %s"
msgstr ""

#: nova/virt/libvirt/utils.py:528
msgid "findmnt tool is not installed"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:67
#, python-format
msgid "Mounted volume: %s"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:135
#, python-format
msgid "Fixing previous mount %s which was not unmounted correctly."
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:157
#, python-format
msgid "Trying to disconnected unmounted volume at %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:196
#, python-format
msgid "VMware vCenter version: %s"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:272
#, python-format
msgid "Moved virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:290
#, python-format
msgid "Copied virtual disk from %(src)s to %(dst)s."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:304
#, python-format
msgid "Deleted virtual disk %s."
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:162
#, python-format
msgid "Image %s is no longer used by this node. Pending deletion!"
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:167
#, python-format
msgid "Image %s is no longer used. Deleting!"
msgstr ""

#: nova/virt/vmwareapi/images.py:381
#, python-format
msgid "Downloaded image file data %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/images.py:385 nova/virt/vmwareapi/images.py:455
msgid "The imported VM was unregistered"
msgstr ""

#: nova/virt/vmwareapi/images.py:447
#, python-format
msgid "Downloaded OVA image file %(image_ref)s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1333
msgid "Destroyed the VM"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1595
#, python-format
msgid "Created folder: %(name)s in parent %(parent)s."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:932
msgid "Created linked-clone VM from snapshot"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1464 nova/virt/xenapi/vmops.py:1709
#, python-format
msgid "Found %(instance_count)d hung reboots older than %(timeout)d seconds"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1468 nova/virt/xenapi/vmops.py:1713
msgid "Automatically hard rebooting"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:464
#, python-format
msgid ""
"The volume's backing has been relocated to %s. Need to consolidate "
"backing disk file."
msgstr ""

#: nova/virt/xenapi/agent.py:396
msgid ""
"XenServer tools installed in this image are capable of network injection."
"  Networking files will not bemanipulated"
msgstr ""

#: nova/virt/xenapi/agent.py:404
msgid ""
"XenServer tools are present in this image but are not capable of network "
"injection"
msgstr ""

#: nova/virt/xenapi/agent.py:408
msgid "XenServer tools are not installed in this image"
msgstr ""

#: nova/virt/xenapi/host.py:76
#, python-format
msgid ""
"Instance %(name)s running on %(host)s could not be found in the database:"
" assuming it is a worker VM and skip ping migration to a new host"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:396
#, python-format
msgid "VBD %s already detached"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:399
#, python-format
msgid ""
"VBD %(vbd_ref)s uplug failed with \"%(err)s\", attempt "
"%(num_attempt)d/%(max_attempts)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:684
#, python-format
msgid "Deleted %s snapshots."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1327
#, python-format
msgid ""
"Image creation data, cacheable: %(cache)s, downloaded: %(downloaded)s "
"duration: %(duration).2f secs for image %(image_id)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2170
#, python-format
msgid "Disconnecting stale VDI %s from compute domU"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2466
msgid "Manipulating interface files directly"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2475
#, python-format
msgid "Failed to mount filesystem (expected for non-linux instances): %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1287
msgid "Starting halted instance found during reboot"
msgstr ""

#: nova/virt/xenapi/vmops.py:1491
msgid "Destroying VM"
msgstr ""

#: nova/virt/xenapi/volumeops.py:65
#, python-format
msgid "Connected volume (vdi_uuid): %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:131
#, python-format
msgid "Dev %(dev_number)s attached to instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:153
#, python-format
msgid "Mountpoint %(mountpoint)s detached from instance %(instance_name)s"
msgstr ""

#: nova/vnc/xvp_proxy.py:84
#, python-format
msgid "Error in handshake format: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:90
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:105
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:125
#, python-format
msgid "Request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:128
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:138
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:145
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:165
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr ""

#: nova/volume/encryptors/luks.py:109
#, python-format
msgid "%s is not a valid LUKS device; formatting device for first use"
msgstr ""

